name: Testing with devbox

on:
  workflow_dispatch
    
jobs:
  devbox-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Run arbitrary commands
        run: devbox run -- pwsh -c "write-host 'Hello from pwsh ğŸğŸğŸ ' "

      - name: Run powershell host
        run: devbox run p-host

      - name: Run powershell test
        run: devbox run p-test  

      - name: show environment
        run: devbox run env-list
           
